name: E2E Tests in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # this is needed to wait for the new docker image to be build and published to the registry
  # so that we can use the image to run the service of the needed commit related version as part of local-env
  # the idea is taken from here https://stackoverflow.com/a/71489231
  docker-build-and-push:
    uses: ./.github/workflows/.reusable-docker-build-and-push.yml

  e2e-karate-tests-in-docker-compose:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Run service via docker-compose and run Karate-tests
      run: |
        # The option --exit-code-from ensures that the command's exit code exactly matches the exit code of the specified service.
        docker compose --profile MockForPullRequest up --exit-code-from inner-circle-invoices-api-karate-tests